spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lolreview.summonerreview.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: your_jwt_secret_key_which_is_long_enough_for_hs256
  expiration: 3600000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html 